/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SnsRouteImport } from './routes/sns'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const SnsRoute = SnsRouteImport.update({
  id: '/sns',
  path: '/sns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/consultations': typeof ConsultationsRoute
  '/content': typeof ContentRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/sns': typeof SnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/consultations': typeof ConsultationsRoute
  '/content': typeof ContentRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/sns': typeof SnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/consultations': typeof ConsultationsRoute
  '/content': typeof ContentRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/sns': typeof SnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cards'
    | '/consultations'
    | '/content'
    | '/dashboard'
    | '/pricing'
    | '/settings'
    | '/shop'
    | '/sns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cards'
    | '/consultations'
    | '/content'
    | '/dashboard'
    | '/pricing'
    | '/settings'
    | '/shop'
    | '/sns'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cards'
    | '/consultations'
    | '/content'
    | '/dashboard'
    | '/pricing'
    | '/settings'
    | '/shop'
    | '/sns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CardsRoute: typeof CardsRoute
  ConsultationsRoute: typeof ConsultationsRoute
  ContentRoute: typeof ContentRoute
  DashboardRoute: typeof DashboardRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  SnsRoute: typeof SnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sns': {
      id: '/sns'
      path: '/sns'
      fullPath: '/sns'
      preLoaderRoute: typeof SnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CardsRoute: CardsRoute,
  ConsultationsRoute: ConsultationsRoute,
  ContentRoute: ContentRoute,
  DashboardRoute: DashboardRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  SnsRoute: SnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
