/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoMakerRouteImport } from './routes/video-maker'
import { Route as TarotPdfRouteImport } from './routes/tarot-pdf'
import { Route as SnsRouteImport } from './routes/sns'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MyShopRouteImport } from './routes/my-shop'
import { Route as FortunePdfRouteImport } from './routes/fortune-pdf'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CardDesignerRouteImport } from './routes/card-designer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatTarotRouteImport } from './routes/chat.tarot'
import { Route as ChatSajuRouteImport } from './routes/chat.saju'
import { Route as ChatRelationRouteImport } from './routes/chat.relation'
import { Route as ChatFreeRouteImport } from './routes/chat.free'
import { Route as ChatCoupleRouteImport } from './routes/chat.couple'

const VideoMakerRoute = VideoMakerRouteImport.update({
  id: '/video-maker',
  path: '/video-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotPdfRoute = TarotPdfRouteImport.update({
  id: '/tarot-pdf',
  path: '/tarot-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const SnsRoute = SnsRouteImport.update({
  id: '/sns',
  path: '/sns',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MyShopRoute = MyShopRouteImport.update({
  id: '/my-shop',
  path: '/my-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const FortunePdfRoute = FortunePdfRouteImport.update({
  id: '/fortune-pdf',
  path: '/fortune-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CardDesignerRoute = CardDesignerRouteImport.update({
  id: '/card-designer',
  path: '/card-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatTarotRoute = ChatTarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSajuRoute = ChatSajuRouteImport.update({
  id: '/saju',
  path: '/saju',
  getParentRoute: () => ChatRoute,
} as any)
const ChatRelationRoute = ChatRelationRouteImport.update({
  id: '/relation',
  path: '/relation',
  getParentRoute: () => ChatRoute,
} as any)
const ChatFreeRoute = ChatFreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => ChatRoute,
} as any)
const ChatCoupleRoute = ChatCoupleRouteImport.update({
  id: '/couple',
  path: '/couple',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card-designer': typeof CardDesignerRoute
  '/chat': typeof ChatRouteWithChildren
  '/consultations': typeof ConsultationsRoute
  '/content': typeof ContentRoute
  '/dashboard': typeof DashboardRoute
  '/fortune-pdf': typeof FortunePdfRoute
  '/my-shop': typeof MyShopRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/sns': typeof SnsRoute
  '/tarot-pdf': typeof TarotPdfRoute
  '/video-maker': typeof VideoMakerRoute
  '/chat/couple': typeof ChatCoupleRoute
  '/chat/free': typeof ChatFreeRoute
  '/chat/relation': typeof ChatRelationRoute
  '/chat/saju': typeof ChatSajuRoute
  '/chat/tarot': typeof ChatTarotRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card-designer': typeof CardDesignerRoute
  '/consultations': typeof ConsultationsRoute
  '/content': typeof ContentRoute
  '/dashboard': typeof DashboardRoute
  '/fortune-pdf': typeof FortunePdfRoute
  '/my-shop': typeof MyShopRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/sns': typeof SnsRoute
  '/tarot-pdf': typeof TarotPdfRoute
  '/video-maker': typeof VideoMakerRoute
  '/chat/couple': typeof ChatCoupleRoute
  '/chat/free': typeof ChatFreeRoute
  '/chat/relation': typeof ChatRelationRoute
  '/chat/saju': typeof ChatSajuRoute
  '/chat/tarot': typeof ChatTarotRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card-designer': typeof CardDesignerRoute
  '/chat': typeof ChatRouteWithChildren
  '/consultations': typeof ConsultationsRoute
  '/content': typeof ContentRoute
  '/dashboard': typeof DashboardRoute
  '/fortune-pdf': typeof FortunePdfRoute
  '/my-shop': typeof MyShopRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/sns': typeof SnsRoute
  '/tarot-pdf': typeof TarotPdfRoute
  '/video-maker': typeof VideoMakerRoute
  '/chat/couple': typeof ChatCoupleRoute
  '/chat/free': typeof ChatFreeRoute
  '/chat/relation': typeof ChatRelationRoute
  '/chat/saju': typeof ChatSajuRoute
  '/chat/tarot': typeof ChatTarotRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/card-designer'
    | '/chat'
    | '/consultations'
    | '/content'
    | '/dashboard'
    | '/fortune-pdf'
    | '/my-shop'
    | '/pricing'
    | '/settings'
    | '/sns'
    | '/tarot-pdf'
    | '/video-maker'
    | '/chat/couple'
    | '/chat/free'
    | '/chat/relation'
    | '/chat/saju'
    | '/chat/tarot'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/card-designer'
    | '/consultations'
    | '/content'
    | '/dashboard'
    | '/fortune-pdf'
    | '/my-shop'
    | '/pricing'
    | '/settings'
    | '/sns'
    | '/tarot-pdf'
    | '/video-maker'
    | '/chat/couple'
    | '/chat/free'
    | '/chat/relation'
    | '/chat/saju'
    | '/chat/tarot'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/card-designer'
    | '/chat'
    | '/consultations'
    | '/content'
    | '/dashboard'
    | '/fortune-pdf'
    | '/my-shop'
    | '/pricing'
    | '/settings'
    | '/sns'
    | '/tarot-pdf'
    | '/video-maker'
    | '/chat/couple'
    | '/chat/free'
    | '/chat/relation'
    | '/chat/saju'
    | '/chat/tarot'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CardDesignerRoute: typeof CardDesignerRoute
  ChatRoute: typeof ChatRouteWithChildren
  ConsultationsRoute: typeof ConsultationsRoute
  ContentRoute: typeof ContentRoute
  DashboardRoute: typeof DashboardRoute
  FortunePdfRoute: typeof FortunePdfRoute
  MyShopRoute: typeof MyShopRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  SnsRoute: typeof SnsRoute
  TarotPdfRoute: typeof TarotPdfRoute
  VideoMakerRoute: typeof VideoMakerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-maker': {
      id: '/video-maker'
      path: '/video-maker'
      fullPath: '/video-maker'
      preLoaderRoute: typeof VideoMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot-pdf': {
      id: '/tarot-pdf'
      path: '/tarot-pdf'
      fullPath: '/tarot-pdf'
      preLoaderRoute: typeof TarotPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sns': {
      id: '/sns'
      path: '/sns'
      fullPath: '/sns'
      preLoaderRoute: typeof SnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-shop': {
      id: '/my-shop'
      path: '/my-shop'
      fullPath: '/my-shop'
      preLoaderRoute: typeof MyShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fortune-pdf': {
      id: '/fortune-pdf'
      path: '/fortune-pdf'
      fullPath: '/fortune-pdf'
      preLoaderRoute: typeof FortunePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card-designer': {
      id: '/card-designer'
      path: '/card-designer'
      fullPath: '/card-designer'
      preLoaderRoute: typeof CardDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/tarot': {
      id: '/chat/tarot'
      path: '/tarot'
      fullPath: '/chat/tarot'
      preLoaderRoute: typeof ChatTarotRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/saju': {
      id: '/chat/saju'
      path: '/saju'
      fullPath: '/chat/saju'
      preLoaderRoute: typeof ChatSajuRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/relation': {
      id: '/chat/relation'
      path: '/relation'
      fullPath: '/chat/relation'
      preLoaderRoute: typeof ChatRelationRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/free': {
      id: '/chat/free'
      path: '/free'
      fullPath: '/chat/free'
      preLoaderRoute: typeof ChatFreeRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/couple': {
      id: '/chat/couple'
      path: '/couple'
      fullPath: '/chat/couple'
      preLoaderRoute: typeof ChatCoupleRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatCoupleRoute: typeof ChatCoupleRoute
  ChatFreeRoute: typeof ChatFreeRoute
  ChatRelationRoute: typeof ChatRelationRoute
  ChatSajuRoute: typeof ChatSajuRoute
  ChatTarotRoute: typeof ChatTarotRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatCoupleRoute: ChatCoupleRoute,
  ChatFreeRoute: ChatFreeRoute,
  ChatRelationRoute: ChatRelationRoute,
  ChatSajuRoute: ChatSajuRoute,
  ChatTarotRoute: ChatTarotRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CardDesignerRoute: CardDesignerRoute,
  ChatRoute: ChatRouteWithChildren,
  ConsultationsRoute: ConsultationsRoute,
  ContentRoute: ContentRoute,
  DashboardRoute: DashboardRoute,
  FortunePdfRoute: FortunePdfRoute,
  MyShopRoute: MyShopRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  SnsRoute: SnsRoute,
  TarotPdfRoute: TarotPdfRoute,
  VideoMakerRoute: VideoMakerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
